Removed debconf

diff --git a/scripts/debian_pkg/DEBIAN/preinst b/scripts/debian_pkg/DEBIAN/preinst
--- a/scripts/debian_pkg/DEBIAN/preinst
+++ b/scripts/debian_pkg/DEBIAN/preinst
@@ -1,23 +1,24 @@
 #!/bin/sh
+set -e
 
 if [ "$1" = install ] || [ "$1" = upgrade ]; then
     echo "Checking MediaWEB dependencies"
 
     if ! [ -x "$(command -v systemctl)" ]; then
-        echo "ERROR! systemctl is not installed."
-        echo
-        echo "To install MediaWEB the system needs to support systemd services."
-        echo
+        echo "ERROR! systemctl is not installed."  1>&2
+        echo "" 1>&2
+        echo "To install MediaWEB the system needs to support systemd services." 1>&2
+        echo "" 1>&2
         exit 1
     else
         echo "systemctl: ok"
     fi
 
     if ! [ -x "$(command -v ffmpeg)" ]; then
-        echo "Warning! ffmpeg is not installed."
-        echo
-        echo "To generate video thumbnails ffmpeg needs to be installed."
-        echo
+        echo "Warning! ffmpeg is not installed." 1>&2
+        echo "" 1>&2
+        echo "To generate video thumbnails ffmpeg needs to be installed." 1>&2
+        echo "" 1>&2
     else
         echo "ffmpeg:    ok"
     fi
@@ -25,8 +26,8 @@ if [ "$1" = install ] || [ "$1" = upgrade ]; then
     systemctl is-active --quiet mediaweb && {
         echo "Stopping MediaWEB service"
         systemctl stop mediaweb || {
-            echo "ERROR! Unable to stop MediaWEB service"
-            echo
+            echo "ERROR! Unable to stop MediaWEB service" 1>&2
+            echo "" 1>&2
             exit 1
         }
     }
@@ -34,8 +35,8 @@ if [ "$1" = install ] || [ "$1" = upgrade ]; then
     systemctl is-enabled --quiet mediaweb 2> /dev/null && {  
         echo "Disabling MediaWEB service"   
         systemctl disable mediaweb || {
-            echo "ERROR! Unable to disable MediaWEB service"
-            echo
+            echo "ERROR! Unable to disable MediaWEB service" 1>&2
+            echo "" 1>&2
             exit 1
         }
     }
diff --git a/scripts/debian_pkg/DEBIAN/prerm b/scripts/debian_pkg/DEBIAN/prerm
--- a/scripts/debian_pkg/DEBIAN/prerm
+++ b/scripts/debian_pkg/DEBIAN/prerm
@@ -1,12 +1,13 @@
 #!/bin/sh
+set -e
 
 if [ "$1" = remove ]; then
 
     systemctl is-active --quiet mediaweb && {
         echo "Stopping MediaWEB service"
         systemctl stop mediaweb || {
-            echo "ERROR! Unable to stop MediaWEB service"
-            echo
+            echo "ERROR! Unable to stop MediaWEB service" 1>&2
+            echo "" 1>&2
             exit 1
         }
     }
@@ -14,8 +15,8 @@ if [ "$1" = remove ]; then
     systemctl is-enabled --quiet mediaweb 2> /dev/null && {  
         echo "Disabling MediaWEB service"   
         systemctl disable mediaweb || {
-            echo "ERROR! Unable to disable MediaWEB service"
-            echo
+            echo "ERROR! Unable to disable MediaWEB service" 1>&2
+            echo "" 1>&2
             exit 1
         }
     }
